<?php

declare(strict_types=1);

namespace Contenir\Db\Model\Tools\Validator;

use Contenir\Db\Model\Metadata\EntityMetadata;
use Contenir\Db\Model\Metadata\FieldRole;
use Contenir\Db\Model\Tools\Generator\TypeMapper;
use Contenir\Db\Model\Tools\Schema\TableSchema;

use function implode;
use function sort;
use function sprintf;

/**
 * Compares #[Id] and #[Version] mapping with the table's primary key,
 * generated columns and column types.
 *
 * @internal
 */
final readonly class KeyChecks
{
    /**
     * @param EntityMetadata<object> $metadata
     *
     * @return list<Issue>
     */
    public static function check(EntityMetadata $metadata, TableSchema $table): array
    {
        $issues = [];
        $key    = self::primaryKey($metadata, $table);
        if (null !== $key) {
            $issues[] = $key;
        }

        foreach ($metadata->identifier as $field) {
            $generated = $table->column($field->columnName)?->generated;
            if (true === $generated && FieldRole::Identifier === $field->role) {
                $issues[] = Issue::warning(sprintf(
                    'Column "%s" is generated by the database; map it with #[Id(generated: true)]',
                    $field->columnName,
                ));
            }

            if (false === $generated && FieldRole::GeneratedIdentifier === $field->role) {
                $issues[] = Issue::error(sprintf(
                    'Column "%s" is mapped #[Id(generated: true)] but the database does not generate it',
                    $field->columnName,
                ));
            }
        }

        $version = null === $metadata->version ? null : $table->column($metadata->version->columnName);
        if (null !== $version && 'int' !== TypeMapper::map($version)->phpType) {
            $issues[] = Issue::error(sprintf('Version column "%s" must be an integer column', $version->name));
        }

        return $issues;
    }

    /**
     * @param EntityMetadata<object> $metadata
     */
    private static function primaryKey(EntityMetadata $metadata, TableSchema $table): ?Issue
    {
        $mapped = $metadata->getIdentifierColumns();
        $actual = $table->primaryKey;
        sort($mapped);
        sort($actual);

        if ([] === $actual) {
            return Issue::warning(sprintf(
                'Table "%s" has no primary key; #[Id] column(s) %s must still be unique',
                $table->name,
                implode(', ', $mapped),
            ));
        }

        if ($mapped !== $actual) {
            return Issue::error(sprintf(
                '#[Id] column(s) %s differ from the primary key %s',
                implode(', ', $mapped),
                implode(', ', $actual),
            ));
        }

        return null;
    }
}
