<?php

declare(strict_types=1);

namespace ContenirTest\Db\Model\Tools\Integration\Validator;

use Contenir\Db\Model\Metadata\AttributeMetadataFactory;
use Contenir\Db\Model\Tools\Schema\SchemaReader;
use Contenir\Db\Model\Tools\Validator\ColumnChecks;
use Contenir\Db\Model\Tools\Validator\FieldChecks;
use Contenir\Db\Model\Tools\Validator\Issue;
use Contenir\Db\Model\Tools\Validator\KeyChecks;
use Contenir\Db\Model\Tools\Validator\RelationChecks;
use Contenir\Db\Model\Tools\Validator\SchemaValidator;
use Contenir\Db\Model\Tools\Validator\TypeCompatibility;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\AuditLog;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\BadJoinUser;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\DriftedUser;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\MisKeyedOrderItem;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\MissingTable;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\StringVersionUser;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Broken\Unmapped;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\OrderItem;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\Tag;
use ContenirTest\Db\Model\Tools\TestAsset\Entity\User;
use ContenirTest\Db\Model\Tools\Trait\TestDatabaseTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

use function array_map;
use function preg_replace;

#[CoversClass(SchemaValidator::class)]
#[CoversClass(ColumnChecks::class)]
#[CoversClass(FieldChecks::class)]
#[CoversClass(KeyChecks::class)]
#[CoversClass(RelationChecks::class)]
#[CoversClass(TypeCompatibility::class)]
#[CoversClass(Issue::class)]
#[Group('integration')]
final class SchemaValidatorTest extends TestCase
{
    use TestDatabaseTrait;

    /**
     * @return array<string, array{string, string}>
     */
    public static function unusableEntityProvider(): array
    {
        return [
            'missing table'   => [MissingTable::class, 'error: Table "nope" does not exist'],
            'invalid mapping' => [
                Unmapped::class,
                'error: Entity "' . Unmapped::class . '" declares no #[Id] property',
            ],
            'unknown class'   => ['Missing', 'error: Class Missing cannot be autoloaded'],
        ];
    }

    /**
     * @return array<string, array{class-string}>
     */
    public static function validEntityProvider(): array
    {
        return [
            'columns, version and many-to-many' => [User::class],
            'belongs-to'                        => [OrderItem::class],
            'generated key'                     => [Tag::class],
        ];
    }

    #[DataProvider('validEntityProvider')]
    #[Test]
    public function matchingMappingsHaveNoIssues(string $className): void
    {
        static::assertSame([], $this->issues($className));
    }

    #[Test]
    public function reportsColumnDrift(): void
    {
        $issues = array_map(
            static fn(string $issue): string => (string) preg_replace(
                '/ is [a-z ]+ \(/',
                replacement: ' is <dialect> (',
                subject: $issue,
            ),
            $this->issues(DriftedUser::class),
        );

        static::assertSame(
            [
                'warning: Column "id" is generated by the database; map it with #[Id(generated: true)]',
                'warning: Property $email is nullable but column "email" is NOT NULL without a default',
                'warning: Property $createdAt is int but column "created_at" is <dialect> (DateTimeImmutable)',
                'error: Column "birthday" allows NULL but property $birthday is not nullable',
                'error: Column "nickname" (property $nickname) does not exist',
            ],
            $issues,
        );
    }

    #[DataProvider('unusableEntityProvider')]
    #[Test]
    public function reportsEntitiesThatCannotBeChecked(string $className, string $issue): void
    {
        static::assertSame([$issue], $this->issues($className));
    }

    #[Test]
    public function reportsKeyMismatches(): void
    {
        static::assertSame(
            [
                'error: #[Id] column(s) user_id differ from the primary key id',
                'error: Column "user_id" is mapped #[Id(generated: true)] but the database does not generate it',
                'warning: Column "id" is NOT NULL without a default but is not mapped, so inserts will fail',
            ],
            $this->issues(MisKeyedOrderItem::class),
        );
    }

    #[Test]
    public function reportsMissingJoinTablesAndColumns(): void
    {
        static::assertSame(
            [
                'error: Join table "user_label" of relation $labels does not exist',
                'error: Join column "user_tag.label_id" of relation $tags does not exist',
            ],
            $this->issues(BadJoinUser::class),
        );
    }

    #[Test]
    public function reportsNonIntegerVersionColumns(): void
    {
        static::assertSame(
            'error: Version column "email" must be an integer column',
            $this->issues(StringVersionUser::class)[0] ?? null,
        );
    }

    #[Test]
    public function warnsAboutTablesWithoutPrimaryKey(): void
    {
        static::assertSame(
            ['warning: Table "audit_log" has no primary key; #[Id] column(s) message must still be unique'],
            $this->issues(AuditLog::class),
        );
    }

    protected function setUp(): void
    {
        $this->setUpTestDatabase();
    }

    /**
     * @return list<string> as "severity: message"
     */
    private function issues(string $className): array
    {
        $validator = new SchemaValidator(new SchemaReader($this->adapter), new AttributeMetadataFactory());

        return array_map(
            static fn(Issue $issue): string => "{$issue->severity->value}: {$issue->message}",
            $validator->validate($className),
        );
    }
}
